### ISSUE TITLE
Update k8s.io/client-go version

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#1556] opened 2019-10-28 16:31 UTC
As I was implementing #1552 I discovered, that we are currently using the outdated version `k8s.io/client-go v11.0.1-0.20190409021438-1a26190bd76a`, which has no support for the new `events.k8s.io` API (see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/events-redesign.md)

k8s.io/client-go version v12.0.0 is the one used in k8s 1.15 and includes support for the new events API, which has better deduplication logic to not impact cluster performance in the case of many similar events.

Can we upgrade to the latest version of client-go?

**Comment by ialidzhikov** [comment] 2019-10-28 18:11
+1

This will be done with #1206 (which requires #1349 and `sigs.k8s.io/controller-runtime@v0.3.0`). I think we can close as duplicate of #1206.

**Closed as completed** 2019-11-04 12:33 UTC
Labels: kind/enhancement
