### ISSUE TITLE
Create network policies for resources in kube-system ns of the Shoot

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1224] opened 2019-07-17 15:12 UTC
End users may deploy network policies which may break connectivity for vpn other system components living in the kube-system ns.

**Comment by vpnachev** [comment] 2019-07-21 13:00
You could check #565, which is basically the same issue as this one.

**Comment by rfranzke** [comment] 2019-07-21 13:03
Yes, let's close this one as a duplicate of #565

**Closed as completed by rfranzke** 2019-07-21 13:03 UTC
