### ISSUE TITLE
Failing to create seed in local setup

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#6548] opened 2022-08-19 12:52 UTC
**How to categorize this issue?**

/area testing
/kind bug

**What happened**:
When creating a seed in a local setup, the seed cannot be ready because of `kube-state-metrics`. `kube-state-metrics` goes into `CrashLoopBackOff` without any error in logs.

**What you expected to happen**:
Should be able to create seed in a local setup.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new shoot and use this new shoot for shooted seed in local setup, check garden namespace in this shoot to confirm `kube-state-metrics` goes into `CrashLoopBackOff`.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.53.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment] 2022-08-22 07:40
Is this reproducible in every case? Can you share some logs of the `kube-state-metrics`?

**Comment by acumino** [comment] 2022-08-22 07:44
> Is this reproducible in every case? Can you share some logs of the `kube-state-metrics`?

Yes. 
Logs of `kube-system-metrics` - 
```
I0819 14:07:07.578744       1 main.go:89] Using collectors deployments,horizontalpodautoscalers,nodes,persistentvolumeclaims,pods,replicasets,statefulsets
I0819 14:07:07.578787       1 main.go:98] Using all namespace
I0819 14:07:07.578796       1 main.go:139] metric white-blacklisting: blacklisting the following items:
W0819 14:07:07.578813       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0819 14:07:07.580649       1 main.go:184] Testing communication with server
F0819 14:07:37.581149       1 main.go:147] Failed to create client: error while trying to communicate with apiserver: Get [https://api.test1.i545932.internal.dev.k8s.ondemand.com:443/version?timeout=32s](https://api.test1.i545932.internal.dev.k8s.ondemand.com/version?timeout=32s): dial tcp: i/o timeout
```

**Comment by unmarshall** [comment] 2022-08-22 11:01
I tried scaling down `kube-system-metrics` - this at least helped to start the seed. It went into `Ready` state. However the shoot creation continues to fail.
Logs from GRM:
```
{"level":"error","ts":"2022-08-22T10:38:22.551Z","msg":"Failed to get API Group-Resources","error":"Get \"[https://api.localtests.mb-garden.internal.dev.k8s.ondemand.com:443/api?timeout=32s](https://api.localtests.mb-garden.internal.dev.k8s.ondemand.com/api?timeout=32s)\": dial tcp: lookup api.localtests.mb-garden.internal.dev.k8s.ondemand.com: i/o timeout","stacktrace":"sigs.k8s.io/controller-runtime/pkg/cluster.New\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go:322\ngithub.com/gardener/gardener/cmd/gardener-resource-manager/app.NewResourceManagerCommand.func1\n\t/go/src/github.com/gardener/gardener/cmd/gardener-resource-manager/app/app.go:124\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/gardener/gardener/vendor/github.com/spf13/cobra/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/gardener/gardener/vendor/github.com/spf13/cobra/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/gardener/gardener/vendor/github.com/spf13/cobra/command.go:902\ngithub.com/spf13/cobra.(*Command).ExecuteContext\n\t/go/src/github.com/gardener/gardener/vendor/github.com/spf13/cobra/command.go:895\nmain.main\n\t/go/src/github.com/gardener/gardener/cmd/gardener-resource-manager/main.go:34\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```
State of pods in the shoot control namespace:
```
cloud-controller-manager-64f9794ff8-fhkmc    0/1     ContainerCreating   0               28m
csi-driver-controller-5f5b46887-9bhm5        0/6     ContainerCreating   0               28m
csi-snapshot-controller-5864987c6f-wtrnr     0/1     ContainerCreating   0               28m
csi-snapshot-validation-858549db67-bnw89     1/1     Running             0               28m
etcd-events-0                                2/2     Running             0               30m
etcd-main-0                                  2/2     Running             0               30m
gardener-resource-manager-54b8f79d86-2rp5z   0/1     CrashLoopBackOff    6 (44s ago)     10m
gardener-resource-manager-75ccd75b66-ghrqv   0/1     CrashLoopBackOff    7 (2m32s ago)   17m
gardener-resource-manager-76cd54b6d-9fdpx    0/1     CrashLoopBackOff    7 (81s ago)     16m
gardener-resource-manager-974c97888-kh2lx    0/1     CrashLoopBackOff    6 (4m33s ago)   13m
kube-apiserver-d666cc4b6-84vpl               2/2     Running             0               28m
kube-controller-manager-7858545696-lh446     0/1     ContainerCreating   0               27m
vpn-seed-server-895d5cb9f-xh6x7              2/2     Running             0               30m
```

**Comment by rfranzke** [comment] 2022-08-22 11:05
Given that this does not happen with `provider-local`, I expect that it's a problem in the respective seed that is used for the local setup.
@ScheererJ might this be related to the recent networking/DNS changes in the respective landscape?

**Comment by ScheererJ** [comment] 2022-08-22 12:23
Apparently, the network policies are not correct for usage of node local dns on the seed, yet. I will investigate and fix this.
For now, please deactivate node local dns on your seed cluster in case you face this issue.

**Comment by rfranzke** [comment] 2022-08-22 12:25
Thanks. I think we should close this issue since it's likely not related to a problem in `gardener/gardener`.
Feel free to `/reopen` if you think different.

/close

**Closed as completed by rfranzke** 2022-08-22 12:25 UTC
Labels: kind/bug, area/testing

**Comment by ashwani2k** [comment] 2022-08-22 13:11
It works @ScheererJ after incorporating your suggestion to disable `nodeLocalDNS`.   Thanks a ton!
