### ISSUE TITLE
hyperkube goes down when we stress node's with workloads beyond the node's default capacity

### ISSUE THREAD

**Issue by ghost** [gardener/gardener#122] opened 2018-04-09 13:36 UTC
How to Reproduce:
create a gardener shoot cluster with one AWS autoscaling worker group with min as one and max as 10.
Run the clusterloader from perf tests repo with step size as 10 and pods as 1500
so initially only one node will be up and as the clusterloader framework runs AWS autoscaling tries to add nodes when workloads goes beyond the existing nodes capacity.
At the moment, where in one side, clusterloader tries to feed more and more pods and AWS tries to scale the nodes, when the node stretches beyond its capacity, the hyperkube process gets crashed multiple times which has to be fixed.
Running Cluster Loader:
This can be run individually from working perf-tests repo or from kubetest in test-infra repo

**Comment by rfranzke** [comment] 2018-04-09 13:49
Duplicate of #79?

**Closed as completed** 2018-04-11 12:20 UTC
