### ISSUE TITLE
Shoot cannot be deleted because of unexisting resource-manager

### ISSUE THREAD

**Issue by schrodit** [gardener/gardener#1214] opened 2019-07-15 09:09 UTC
**What happened**:
A shoot that was created 1 month ago (before the resource manager was introduced) and hibernated since then, could not be deleted.
Gardener is unable to delete the shoot because it tries to scale up the `resource manager deployment` which was never created for the shoot.

**What you expected to happen**:
The shoot clusters can be successfully deleted/wokenup.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot on a gardener with version `<0.26.0` and hibernate the shoot.
Update Gardener to version 0.26.4 and try to delete the hibernated shoot.

**Environment**:

- Gardener version: 0.26.4
- Cloud provider or hardware configuration: aws

**Comment by ialidzhikov** [comment] 2019-07-15 09:13
Duplicate of #1194.
You can close in favour of the referenced issue.

**Closed as completed** 2019-07-15 10:12 UTC
Labels: kind/bug
