### ISSUE TITLE
There is no User-Data field in core.Worker

### ISSUE THREAD

**Issue by qiffang** [gardener/gardener#2038] opened 2020-03-11 15:21 UTC
**What would you like to be added**:
I want to add user data configuration and pass it to VM.
But there is not field in worker object of core.

And i saw gardener use the operationsystemconfig cr to set the userdata field in worker object of extensions version.

If i want to pass user data content to node, does that mean I need to add another operationsystemconfig cr?
**Why is this needed**:

**Comment by rfranzke** [comment] 2020-03-11 18:25
Hi @qiffang, can you elaborate more on your use-case? This is by design - the user-data sent to machines shall only be used to install the bare minimum that is required to run directly on the VM - kubelet, health scripts, logrotate config, not much more. Everything else is installed via Kubernetes means (DaemonSets, ...).

**Comment by qiffang** [comment] 2020-03-12 01:51
@rfranzke 
Thanks for your response soon.
I want to pass these data to machines when gardener startup vms.
For example
```
...
 # mount local ssd disks
mount -a
cat <<EOF > /etc/security/limits.d/xxx.conf
root        soft        nofile        1000000
...
 sed -i 's/LimitNOFILE=infinity/LimitNOFILE=1048576/' /etc/systemd/system/docker.service
...

 systemctl daemon-reload
 systemctl restart docker
```
Thanks

**Comment by rfranzke** [comment] 2020-03-12 06:59
Hello @qiffang, I'm afraid this is not supported for end-users directly. What could be an option is to enhance the operating system config extensions (https://github.com/gardener/gardener-extension-os-coreos, for example) and allow configuring additional things via the `providerConfig` field in the `extensions.gardener.cloud/v1alpha1.OperatingSystemConfig` resource to allow certain configuration for additional settings on the disks. Though, why can't you do this via a `DaemonSet` that runs on all VMs?

**Comment by majst01** [comment] 2020-03-12 06:59
For mounting local disks you can probably use our csi-lvm which will create pv(c) from local disks.

https://github.com/metal-stack/csi-lvm

**Comment by timuthy** [comment] 2020-03-24 20:32
@qiffang do the proposed solutions work for you or do you want to keep this issue open to discuss further?

**Comment by vpnachev** [comment] 2020-03-30 13:16
@qiffang I am closing this issue now. If you need further assistance, please re-open.

**Closed as completed by vpnachev** 2020-03-30 13:16 UTC
Labels: kind/enhancement
