### ISSUE TITLE
Shoot clusters incorrectly marked with `ERR_INFRA_DEPENDENCIES`

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/gardener#5440] opened 2022-02-14 09:01 UTC
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:

Shoot clusters have been marked as user issuers, but the underlying errors are only timeout problems.

Here are three cases:

- Case 1:

```txt
Action required
There is a problem with your secret sap-skr-prd-xxxx: Infrastructure operation failed as unmanaged resources exist in your cloud provider account. Please delete all manually created resources related to this Shoot. 
task "Deploying backup entry" failed: an error on the server ("Internal Server Error: \"/apis/core.gardener.cloud/v1beta1/namespaces/garden-xxx/backupentries/shoot--xxx--yyy--14b043a2-187c-4af0-9743-ec434b3334c0\": Post \"https://virtual-garden-kube-apiserver:443/apis/authorization.k8s.io/v1/subjectaccessreviews?timeout=10s\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)") has prevented the request from succeeding (patch backupentries.core.gardener.cloud shoot--xxx--yyy--14b043a2-187c-4af0-9743-ec434b3334c0)
task "Deploying external domain DNS record" failed: Error while waiting for DNSRecord shoot--xxx--yyy/yyy-external to become ready: error during reconciliation: Error reconciling dnsrecord: could not create or update DNS recordset in zone Z1XXXXX with name api.yyy.xxx.shoot.live.zzz, type A, and values [20.xx.xx.xx]: could not wait for client-side route53 rate limiter: rate: Wait(n=1) would exceed context deadline
```

- Case 2:

```txt
Action required
There is a problem with your secret sap-skr-prd-xxx: Infrastructure operation failed as unmanaged resources exist in your cloud provider account. Please delete all manually created resources related to this Shoot. 
task "Waiting until shoot infrastructure has been reconciled" failed: an error on the server ("Internal Server Error: \"/apis/core.gardener.cloud/v1beta1/namespaces/garden-xxx/shoots/yyy\": Post \"https://virtual-garden-kube-apiserver:443/apis/authorization.k8s.io/v1/subjectaccessreviews?timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)") has prevented the request from succeeding (get shoots.core.gardener.cloud yyy)
task "Deploying internal domain DNS record" failed: Error while waiting for DNSRecord shoot--xxx--yyy/yyy-internal to become ready: error during reconciliation: Error reconciling dnsrecord: could not create or update DNS recordset in zone ZXXX with name api.yyy.xxx.internal.zzz, type A, and values [20.xx.xx.xx]: could not wait for client-side route53 rate limiter: rate: Wait(n=1) would exceed context deadline
task "Deploying external domain DNS record" failed: Error while waiting for DNSRecord shoot--xxx--yyy/yyy-external to become ready: error during reconciliation: Error reconciling dnsrecord: could not create or update DNS recordset in zone ZYYY with name api.yyy.xxx.shoot.live.zzz, type A, and values [20.xx.xx.xx]: could not wait for client-side route53 rate limiter: rate: Wait(n=1) would exceed context deadline
```

- Case 3:

```txt
Action required
There is a problem with your secret sap-skr-xxx: Infrastructure operation failed as unmanaged resources exist in your cloud provider account. Please delete all manually created resources related to this Shoot. 
task "Waiting until shoot infrastructure has been reconciled" failed: an error on the server ("Internal Server Error: \"/apis/core.gardener.cloud/v1beta1/namespaces/garden-xxx/shoots/yyy\": Post \"https://virtual-garden-kube-apiserver:443/apis/authorization.k8s.io/v1/subjectaccessreviews?timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)") has prevented the request from succeeding (patch shoots.core.gardener.cloud yyy)  ```
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.39.3
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment] 2022-02-14 15:40
Thanks for opening this issue @MartinWeindel.
In all three listed cases, the cause for wrong classification seems to be failed requests to the garden cluster like:
```
Internal Server Error: \"/apis/core.gardener.cloud/v1beta1/namespaces/ ...
```

`Internal Server Error` is matched by the `ERR_INFRA_DEPENDENCIES` regex: https://github.com/gardener/gardener/blob/3bd8b8618c3ae13e08204024c3b4bd967872432d/pkg/apis/core/v1beta1/helper/errors.go#L59 which is simply too generalized.

We would like to fix this issue by reworking the error code mapping approach in general.
Let's close this issue in favor of https://github.com/gardener/gardener/issues/5444, which outlines a proposal for this.
/close

**Closed as completed by timebertt** 2022-02-14 15:40 UTC
Labels: kind/bug, area/control-plane
