### ISSUE TITLE
BackupEntry reconcilition blocks for 24 hours or less when the gardenlet is restarted.

### ISSUE THREAD

**Issue by vlvasilev** [gardener/gardener#4540] opened 2021-08-20 18:51 UTC
**How to categorize this issue?**

/area backup
/kind bug
/priority 3

**What happened**:
During normal Shoot reconciliation flow the `BackupEntry` in the Gardener cluster will be annotated with `gardener.cloud/operation=reconcile`. This will change the observed generation and the BE will be caught by the  [`backupEntryUpdate()`](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/gardenlet/controller/backupentry/backup_entry_controller.go#L49) function of the [BE controller](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/gardenlet/controller/backupentry/backup_entry.go#L58).  The only condition that this function checks before putting the BE into the worker's queue is if the current generation matches the observed one. If so it puts the BE into the queue. Then into  [reconcileBackupEntry](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/gardenlet/controller/backupentry/backup_entry_reconciler.go#L97) the last observed generation will be [updated](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/gardenlet/controller/backupentry/backup_entry_reconciler.go#L108) with the current one. This will prevent status updates of BE to put the resource in the worker queue. Then the [Actuator](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/gardenlet/controller/backupentry/backup_entry_reconciler.go#L123) successfully reconcile the BE which status is updated on the next [line](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/gardenlet/controller/backupentry/backup_entry_reconciler.go#L139). After updating the BE status the `gardenlet` is suddenly restarted. We miss the last [step](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/gardenlet/controller/backupentry/backup_entry_reconciler.go#L144) where we remove the operation annotation.
On the next start the BE will be catch by the [backupEntryAdd()](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/gardenlet/controller/backupentry/backup_entry_controller.go#L28) which will send the BE into the queue only if:
1. [There is a deletion timestamp](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/controllerutils/miscellaneous.go#L100).
2. [Current generation is different from the observed one](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/controllerutils/miscellaneous.go#L104).
3. [The last operation is not succeeded](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/controllerutils/miscellaneous.go#L108).
4. [24h have passed since wast operation](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/controllerutils/miscellaneous.go#L116).

In this case, there is no deletion timestamp, the generations are the same, the last operation was successful and this 24h period is not expired.
So as the BE already has the `gardener.cloud/operation=reconcile` annotation, the next shoot reconciliation flow will not update the resource, which will not change the current generation, and thus the reconciliation will be skipped until 24h have passed since the last operation.
The `gardenlet` starts to complain that no controller is peaking up the BE and the cluster enters in an error state.

**What you expected to happen**:
The `gardener.cloud/operation=reconcile` to be removed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
As a solution, we could either add to the worker queue BE with annotation gardener.cloud/operation=reconcile` when passing to [backupEntryAdd()](https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/gardenlet/controller/backupentry/backup_entry_controller.go#L28) or to remove it at the beginning of the same function.
**Environment**:

- Gardener version: v1.28.2
- Kubernetes version (use `kubectl version`): 1.19.10
- Cloud provider or hardware configuration: aws
- Others:

**Comment by rfranzke** [comment] 2021-08-23 05:58
Thanks for the well-written description! Good finding. IMO, the `operation` annotation should be removed right after increasing the generation in the `registry` package, similar to how it's done for `Shoot` resources (https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/registry/core/shoot/strategy.go#L92-L107). We should also check (and potentially adapt) similar handling for other resources if we get already on it.

**Comment by stoyanr** [comment] 2021-08-23 15:36
@rfranzke I would also like to do it as you propose, but I am afraid this will interfere with the current handling, as the operation annotation is also used to determine the current operation type (reconcile or restore) in the reconciler itself, see https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/gardenlet/controller/backupentry/backup_entry_reconciler.go#L109-L110. 

The only really safe place to remove the annotation is right after the above 2 lines, since at this point `operationType` is initialized, but `status.observedGeneration` is not yet updated (it's updated immediately after that, see https://github.com/gardener/gardener/blob/077b71bddce44942018640f0bae69622a9103e66/pkg/gardenlet/controller/backupentry/backup_entry_reconciler.go#L113). I tested this approach and I am no longer able to reproduce the problem, no matter where I put a `panic` to crash the gardenlet.

So, unless you have strong objections, I will fix it this way. I also don't think that the problem applies to any other resource. I looked at `BackupBucket` but it seems the operation annotation is not used there (not added and not removed), even though it's checked in `strategy.go`. All other resources either don't check this annotation in `strategy.go`, or already remove it there (as for `Shoot`).

**Comment by rfranzke** [comment] 2021-08-24 06:13
Thanks for looking into it, very interesting. I'm wondering why the reconcile/migrate/restore behaviour for `BackupEntry`s differs from `Shoot`s. Is there a reason to not implement it the exact same way? Why are `BackupEntry`s "so special" in those regards?

**Comment by stoyanr** [comment] 2021-08-24 07:16
@rfranzke It's rather the Shoot that is special. It basically doesn't need the operation annotation value, because:
* It's possible to determine if the shoot should be migrated (and therefore set the operation type in `status` to `migrate`) by looking at the seed name in spec vs. status.
* At the end of the migration flow, the operation type in `status` can be simply be set to `restore`.

For any other resource that needs to distinguish between reconcile and restore, the shoot reconciliation flow simply sets the operation annotation and relies on the respective controller to figure out what to do. The `BackupEntry` is right now the only garden cluster resource for which this is done, but if there were others, it would be natural to handle them in this way as well. Therefore, for all other resources besides the Shoot, it would not be possible to remove the operation annotation in `strategy.go`.

**Closed as completed** 2021-08-31 07:19 UTC
Labels: kind/bug, area/backup, priority/3
