### ISSUE TITLE
Add networkpolicies into kube-system namespace

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#1655] opened 2019-11-25 16:12 UTC
**What would you like to be added**:
Networkpolicies should be added into the kube-system namespace of shoots that will allow necessary communication between components.

**Why is this needed**:
If users deploy their own networkpolicies into the kube-system namespace it can break the shoot cluster or prevent the shoot cluster from being properly monitored.

**Comment by rfranzke** [comment] 2019-11-25 16:15
Duplicate of #565

**Closed as completed by rfranzke** 2019-11-25 16:15 UTC
Labels: kind/enhancement
