### ISSUE TITLE
Dynamically set allow-to-seed-apiserver network policy

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#1452] opened 2019-09-24 09:38 UTC
**What would you like to be added**:
A controller that dynamically sets the network policy `allow-to-seed-apiserver`.
**Why is this needed**:
Currently, the network policy `allow-to-seed-apiserver` allows traffic to almost every IP. To create a more secure network policy, we need a controller that will create this network policy with the seed-apiserver IP.

**Comment by rfranzke** [comment] 2020-05-25 05:12
Duplicate of #2287
I'm closing this one as #2287 provides more information.
/close

**Closed as completed** 2020-05-25 05:12 UTC
Labels: kind/enhancement
