### ISSUE TITLE
Deletion of managed seeds fails

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/gardener#3890] opened 2021-04-19 09:14 UTC
**How to categorize this issue?**

/area robustness
/kind bug
/priority 3

**What happened**:
I tried to delete a `seed` created by a `ManagedSeed` resource by deleting the `ManagedSeed` resource again. The seed itself gets deleted, but deletion of the `ManagedSeed` resource hangs with the error message
```
Could not unregister shoot garden/aws seed: could not delete gardenlet from shoot garden/aws: render error in "gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml": template: gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml:15:17: executing "gardenlet/charts/runtime/templates/secret-kubeconfig-garden-bootstrap.yaml" at <required ".Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig is required" .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig>: error calling required: .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.kubeconfig is required
```

This happens independently of whether `ServiceAccount` or `BootstrapToken` is set in `spec.gardenlet.bootstrap` in the `ManagedSeed` resource manifest.

**What you expected to happen**:
Deletion of the `ManagedSeed` resource should delete the corresponding seed (which it does) and run through without errors (which it currently does not).

**How to reproduce it (as minimally and precisely as possible)**:
Create a `ManagedSeed` resource and then delete it again.

**Anything else we need to know?**:

**Environment**:

- Gardener version: `v1.20.3`
- Kubernetes version (use `kubectl version`): `1.18.6` (client) and `1.18.3` (cluster)
- Cloud provider or hardware configuration: AWS
- Others: landscape created with garden-setup

**Comment by stoyanr** [comment] 2021-05-12 09:04
@Diaphteiros Is the issue still reproducible with latest gardener? If yes, could you please copy / attach the `ManagedSeed` resource used to reproduce this issue?

> Create a `ManagedSeed` resource and then delete it again.

This works in general, I assume the error is only reproducible under specific circumstances, but it's hard for me to guess what.

**Comment by timebertt** [comment] 2021-05-12 09:36
FYI: the renderer error is similar to https://github.com/gardener/gardener/issues/4002

**Comment by stoyanr** [comment] 2021-05-12 12:31
@timebertt Yes, it's a duplicate. I would say let's close this ticket since the other one has more details.
/duplicate #4002

**Comment by stoyanr** [comment] 2021-05-13 16:52
Reopened this so we can debug. I did manage to reproduce the issue, but only by introducing in the parent gardenlet configuration a few lines that should not be there:

```yaml
gardenClientConnection:
  ...
  bootstrapKubeconfig:
    name: gardenlet-kubeconfig-bootstrap
    namespace: garden
```

@Diaphteiros Could you please confirm that you parent gardenlet configuration (can be found the `garden/gardenlet-configmap` configmap for the gardenlet responsible for the shoot that is registered as seed) contains the above lines? Or simply reproduce the issue and let me take a look?

I can introduce a fix that works with this situation, but I would like to double-check that it's actual caused by this, and not by something else.

**Comment by stoyanr** [comment] 2021-05-17 15:11
Thanks to @Diaphteiros I was able to confirm that the above configuration could indeed be found on soil clusters, where `gardenlet` is not deployed via a managed seed. I will prepare a fix shortly.

**Closed as completed** 2021-05-18 09:04 UTC
Labels: kind/bug, triage/duplicate, area/robustness, priority/3
