### ISSUE TITLE
Managed Resource `APPLIED` status is false as "apiserver-proxy" service had clusterIP other than "None"

### ISSUE THREAD

**Issue by ary1992** [gardener/gardener#5631] opened 2022-03-23 03:09 UTC
**How to categorize this issue?**

/kind bug

**What happened**:
While on DOD (CW12), I came across an issue on Canary landscape , where for one of the shoot `SC tile was red` with the following error on dashboard:

```
Could not apply all new resources: 1 error occurred: error during apply of object "v1/Service/kube-system/apiserver-proxy": Service "apiserver-proxy" is invalid: spec.clusterIPs[0]: Invalid value: []string{"None"}: may not change once set
```

On the control plane of shoot , it was found that  managed resource `shoot-core` `Applied` status was `false`.
```
$ k get mr

NAME         CLASS   APPLIED   HEALTHY   AGE
shoot-core           False     True      48d
``` 

`apiserver-proxy` service had following entries under spec section (default value should be "None" for `clusterIP ` and `clusterIPs` )
```
$ k get svc -n kube-system apiserver-proxy -oyaml

...
spec:
  clusterIP: 100.68.73.224
  clusterIPs:
  - 100.68.73.224
...
```

`managedresource-shoot-core` is the `secretRefs` under spec section of `shoot-core` managed resource. It contains `components_charts_apiserver-proxy_templates_apiserver-proxy-service.yaml` in base64 encoded format as one of the data.

```
apiVersion: v1
kind: Service
metadata:
  name: apiserver-proxy
  namespace: kube-system
  labels:
    gardener.cloud/role: system-component
    origin: gardener
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 16910
    protocol: TCP
  selector:
    app: kubernetes
    role: apiserver-proxy
```

Temporary Fix : 
1. Delete the `apiserver-proxy` service.
2. On reconcilation `apiserver-proxy` service will be created with : 
```
spec:
  clusterIP: None
  clusterIPs:
  - None
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- Target the shoot of a cluster.
- Delete `kube-proxy` service.
- Create `kube-proxy` service with no clusterIP and clsuterIPs field (those will auto assigned). Something like this :
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    resources.gardener.cloud/description: |-
      DO NOT EDIT - This resource is managed by gardener-resource-manager.
      Any modifications are discarded and the resource is returned to the original state.
    resources.gardener.cloud/origin: 2a540a5c-1b8c-11e8-b291-0a580a2c025a:shoot--i546764--ary-seed-az/shoot-core
  labels:
    gardener.cloud/role: system-component
    origin: gardener
    shoot.gardener.cloud/no-cleanup: "true"
  name: apiserver-proxy
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 16910
    protocol: TCP
    targetPort: 16910
  selector:
    app: kubernetes
    role: apiserver-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```  
- After this `shoot-core` managed resource's `APPLIED` status will become false and shoot's SC tile become red.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

cc @vpnachev

**Comment by rfranzke** [comment] 2022-03-23 08:54
https://github.com/gardener/gardener/blob/be6feb277a71c24655f7ff121c29119360f56773/pkg/apis/resources/v1alpha1/types.go#L28-L30 could be used for this scenario if we decide to do something about it in the first place.

**Comment by vpnachev** [comment] 2022-03-23 08:58
For k8s clusters 1.20+ it is nice to manage the `service.spec.clusterIPs` field which is currently not implemented https://github.com/gardener/gardener/blob/v1.42.3/charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-service.yaml. 

Ref for the service change k8s: https://github.com/kubernetes/kubernetes/pull/95894

**Comment by ialidzhikov** [comment] 2022-03-23 09:06
> https://github.com/gardener/gardener/blob/be6feb277a71c24655f7ff121c29119360f56773/pkg/apis/resources/v1alpha1/types.go#L28-L30
> 
> could be used for this scenario if we decide to do something about it in the first place.

As shared in the daily I would not vote to do something similar. The steps to reproduce seem to be too "artificial" - one has to delete the Service and recreate it from a new updated spec (no clusterIP set). I think we could list a lot of similar potential issues - one can delete the coredns Deployment, then create a new Deployment with updates `.spec.selector`, then the ManagedResource should fail in a similar way with reason that `.spec.selector` is immutable. Feel free to correct me if my understanding of the issue is wrong.

>For k8s clusters 1.20+ it is nice to manage the service.spec.clusterIPs field which is currently not implemented https://github.com/gardener/gardener/blob/v1.42.3/charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-service.yaml.

If I see correctly we don't specify `clusterIPs` for any of our Services. If the apiserver conversion logic already takes care of it, I think we should be fine.

I would rather vote simply ignore similar issue for now and ask end users to do not do similar things.

**Comment by acumino** [comment] 2022-04-11 08:33
Should we close this issue as @ialidzhikov suggested the steps to reproduce this error is not very realistic?

**Comment by acumino** [comment] 2022-04-11 09:36
> > https://github.com/gardener/gardener/blob/be6feb277a71c24655f7ff121c29119360f56773/pkg/apis/resources/v1alpha1/types.go#L28-L30
> > 
> > could be used for this scenario if we decide to do something about it in the first place.
> 
> As shared in the daily I would not vote to do something similar. The steps to reproduce seem to be too "artificial" - one has to delete the Service and recreate it from a new updated spec (no clusterIP set). I think we could list a lot of similar potential issues - one can delete the coredns Deployment, then create a new Deployment with updates `.spec.selector`, then the ManagedResource should fail in a similar way with reason that `.spec.selector` is immutable. Feel free to correct me if my understanding of the issue is wrong.
> 
> > For k8s clusters 1.20+ it is nice to manage the service.spec.clusterIPs field which is currently not implemented https://github.com/gardener/gardener/blob/v1.42.3/charts/shoot-core/components/charts/apiserver-proxy/templates/apiserver-proxy-service.yaml.
> 
> If I see correctly we don't specify `clusterIPs` for any of our Services. If the apiserver conversion logic already takes care of it, I think we should be fine.
> 
> I would rather vote simply ignore similar issue for now and ask end users to do not do similar things.

The steps to reproduce this is not very realistic also we have not seen any other occurrence of this issue. 
/close

**Closed as completed by acumino** 2022-04-11 09:36 UTC
Labels: kind/bug
