### ISSUE TITLE
Discard logs for hibernated and testing clusters

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#2252] opened 2020-04-29 08:41 UTC
**What would you like to be added**:
Throw away logs for `shoot-*` namespace that have no `elasticsearch` running. 

**Why is this needed**:
The `fluentd-es` is buffering pod logs from the whole seed cluster.
For shoot clusters that are hibernated or with `spec.purpose=testing` there is no pods backing the `elasticsearch-logging` service. However, fluentd is not aware of this and is trying to send logs there. The result is that `fluentd-es` is scaled to maximum employing all of its memory for the buffers.

Some options to mitigate this is:
1. Deploy a black hole pod instead of the elasticsearch that will accept the logs and write them in `/dev/null`.
1. Implement a [golang output plugin](https://docs.fluentbit.io/manual/development/golang-output-plugins) [1] that has a notion about gardener and can drop logs for shoot clusters without elasticsearch.

[1] https://github.com/fluent/fluent-bit/blob/81deab2bb042c814cee964563c12e8bdd55d8af3/GOLANG_OUTPUT_PLUGIN.md 

cc @donistz

**Comment by vpnachev** [comment] 2020-05-07 08:05
Another options is to add `fluentbit.io/exclude=true` annotation in the pod templates for the hibernated shoots and those with `purpose=testing`. In this way fluentbit will drop logs from these pods.

FYI, there is a bug in fluentbit, the annotation is honored only for newly created pods - https://github.com/fluent/fluent-bit/issues/1142

**Comment by ialidzhikov** [comment] 2020-05-07 08:20
I agree that ignoring testing purpose Shoots would be an improvement.
For the issue that @vlerenc and @rfranzke reported beginning of this week for the "hanged" logging in one of the Seeds - as far as I see there are no Shoots with testing purpose on that Seed. So probably the issue is another one?

**Comment by vlerenc** [comment] 2020-05-07 09:00
We also had the TF pod issue, where it was triggered again and again. @vlvasilev opened #2253. 

Together, i.e. this and the other issue, we may have identified two main suspects. However, there is no guarantee, but we can't have an infinitely scaling logging infrastructure either, so until we notice another issue, I hope these two issues bring us back our logs.

With Augustus: "Oh Varus, give me back my ~~legions~~ logs, please". I took the liberty to append the "please". ;-)

Since without logs, we are kind of screwed, can we please fix that rather sooner than later?

/priority/critical

**Comment by ialidzhikov** [comment] 2020-05-08 08:29
Long time ago @rfranzke asked "why?" about https://github.com/gardener/gardener/pull/1924. Generally I want to write something about it:
- It sucks the way new feature is merged into g/g. In the logging case it is 1 PR that introduce the feature and n following PR that fix (try to make usable) this feature.
https://github.com/gardener/gardener/pull/176 is merged with the following Easter eggs (@rfranzke, was that the right term?):
  - https://github.com/gardener/gardener/pull/616 (coredns producing huge amount of logs, was the logging tested/enabled at all before that?)
  - https://github.com/gardener/gardener/pull/681
  - https://github.com/gardener/gardener/pull/902 (that one was "interesting" one requiring "workarounds" in upstream plugin as fluentd was discarding logs of woken up Shoots because of hibernated ones (1 buffer queue is used and the whole queue was discarded when there is a failure because of hibernated Shoot))
  - https://github.com/gardener/gardener/pull/1017 (was even fluentd successfully scaled to 2-3 replicas before that as HPA and seed controller were all the time thrashing and setting replica count to 1 (seed-controller) and after that to n (HPA)?)
  - Probably there are more, I just don't want to dig further.

Generally because of the reasons above I (just nit spotter and typo fixer) personally have no more "logging fuel".

**Comment by rfranzke** [comment] 2020-05-25 04:04
/close
as the issue should be fixed by #2320

**Closed as completed by rfranzke** 2020-05-25 04:04 UTC
Labels: kind/enhancement, area/logging, priority/2
