### ISSUE TITLE
[Control Plane Engineering] Scaling recommendations for the API Server of the seed cluster

### ISSUE THREAD

**Issue by PadmaB** [gardener/gardener#754] opened 2019-02-20 05:41 UTC
# Story 
* As an administrator, I want to be able to manage larger seed clusters, with ~500 to 1000 nodes the API Server of the seed cluster should be able to support the load
* As an administrator, I want scaling recommendations for API Server to be able to support larger seed clusters

# Acceptance Criteria
- [ ] Evaluate and recommend the parameters like CPU, memory for API Server to be able to support larger seed clusters

- [ ] Integrate the above recommendations with Gardener

- [ ] With this insight, it should be possible to derive recommendations for the API Server of the Shoot Cluster based on the users workload

**Comment by vlerenc** [comment] 2019-04-10 04:27
Can't we close this one as duplicate of the more generic #885?

**Closed as completed** 2019-08-02 07:10 UTC
Labels: kind/enhancement, area/performance, area/robustness, component/gardener, topology/seed, area/control-plane, area/auto-scaling
