### ISSUE TITLE
Error code for misconfigured `PodDisruptionBudget`s blocking machine drain processes

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#3020] opened 2020-10-21 16:57 UTC
**How to categorize this issue?**

/area ops-productivity
/kind enhancement
/priority normal

**What would you like to be added**:
We can reuse the `ERR_CONFIGURATION_PROBLEM` error code to classify shoot errors in which a misconfigured `PodDisruptionBudget` (min available=1), e.g. for istio, blocks the machine drain process.
This is to hide it from the erroneous shoot list in the Gardener Dashboard, and to quickly categorize what the problem is.

Similar to how the shoot care controller detects problematic webhooks, it could detect problematic pod disruption budgets, and write a new constraint into the `Shoot`'s `.status.constraints[]` list.

**Why is this needed**:
In some cases, such misconfigured `PodDisruptionBudget`s created by end-users, e.g. for istio, which leads to a long-visible error message:

  ```text
  task "Waiting until shoot worker nodes have been reconciled" failed: Error while waiting for Worker shoot--foo--bar/bar to become ready: extension encountered error during reconciliation: Error reconciling worker: Failed while waiting for all machine deployments to be ready: 'retry failed with context deadline exceeded, last error: Waiting until all old machines are drained and terminated. Waiting for 2 machine(s)  ...'
  ```

**Comment by ialidzhikov** [comment] 2021-01-20 10:46
> Similar to how the shoot care controller detects problematic webhooks, it could detect problematic pod disruption budgets, and write a new constraint into the `Shoot`'s `.status.constraints[]` list.

Do we want to have this check for misconfigured PodDisruptionBudgets as constraint to allow components like the g/dashboard to read, interpret it and show warnings about it? I am asking because I was wondering whether to start with the constraint approach or to implement the error code handling without the constraint approach.

**Comment by rfranzke** [comment] 2021-01-20 10:49
I guess it would be helpful for the end-users if the Dashboard can display a warning about this (cc @gardener/dashboard-maintainers), so having both would be great :)

**Comment by timebertt** [comment] 2021-01-21 08:00
I guess, the constraints are one option and also fit semantically.
The other option would be to add error codes to the `EveryNodeReady` condition, right?
What would be the better option then?

**Comment by ialidzhikov** [comment] 2021-01-21 15:08
> I guess, the constraints are one option and also fit semantically.
The other option would be to add error codes to the EveryNodeReady condition, right?
What would be the better option then?

Hm, good question. If we pick up the condition approach, would it be okay to fail the `EveryNodeReady` condition for misconfigured PDB that can cause troubles only when the node is drained?
My approach for now is to introduce a new constraint of type `EveryPodEvictionPossible` (naming can be adapted, if there are better suggestion) that checks for misconfigured PDBs. We can also fail the `MaintenancePreconditionsSatisfied` constraint when the `EveryPodEvictionPossible` is false. I initially spent a lot of time thinking whether to add the check for PDBs as new constraint or to check it as part of `MaintenancePreconditionsSatisfied` constraint. Initially I didn't want to add a new constraint just because the status is becoming too verbose. And finally decided to have it as separate constraint and to make `MaintenancePreconditionsSatisfied` dependent of it. Opinion/objections are welcome.
Also this issue suggest reusing the existing error code `ERR_CONFIGURATION_PROBLEM` but it is a non-retryable error code. In our case with PDBs we need a retryable error code as we don't want to stop retrying the Shoot reconcile. And I was thinking about introducing `ERR_RETRYABLE_CONFIGURATION_PROBLEM`.

**Comment by timuthy** [comment] 2021-01-22 07:44
Thanks for driving this topic so thoroughly @ialidzhikov.

> And finally decided to have it as separate constraint and to make MaintenancePreconditionsSatisfied dependent of it.

Wouldn't the `MaintenancePreconditionsSatisfied` then be just a duplicate of the `EveryPodEvictionPossible` condition (with a different type of course)? So I wonder if a specific `reason` can be sufficient.

> Also this issue suggest reusing the existing error code ERR_CONFIGURATION_PROBLEM but it is a non-retryable error code. In our case with PDBs we need a retryable error code as we don't want to stop retrying the Shoot reconcile. And I was thinking about introducing ERR_RETRYABLE_CONFIGURATION_PROBLEM.

SGTM

**Comment by ialidzhikov** [comment] 2021-01-22 08:41
> Wouldn't the MaintenancePreconditionsSatisfied then be just a duplicate of the EveryPodEvictionPossible condition (with a different type of course)? So I wonder if a specific reason can be sufficient.

Currently `MaintenancePreconditionsSatisfied` performs the same checks as in `HibernationPossible`. If we add the check to  the `MaintenancePreconditionsSatisfied` constraint directly (without a separate constraint) and make gardenlet or generic worker actuator to respect it, then we would mark as configuration problem also cases in which there is a problematic webhook during rolling update - and this is exactly the case where I was wondering, reading https://github.com/gardener/gardener/issues/3122 I get that such problematic webhooks might (or might not) cause issues.
WDYT?

**Comment by timuthy** [comment] 2021-01-22 09:21
> If we add the check to the MaintenancePreconditionsSatisfied constraint directly (without a separate constraint) and make gardenlet or generic worker actuator to respect it, then we would mark as configuration problem also cases in which there is a problematic webhook during rolling update

I think this only happens if it solely looks at the constraint `type` right? In general it should also understand the reason and react accordingly.

**Comment by ialidzhikov** [comment] 2021-01-22 19:18
Well, finally I have a draft PR that works and misconfigured PodDisruptionBudgets are properly flagged (WOW!!)- see https://github.com/ialidzhikov/gardener/tree/enh/pdb-checks (excuse me for the missing unit tests and doc strings). I have to admit that I am not happy at all with it as on at least 2 places in the generic worker actuator I have to check whether we have a case with misconfigured PodDisruptionBudgets. I strongly believe that machine-controller-manager should maintain similar errorCodes in the Machine status. It is not the job of provider extension to check similar things and it simply does not scale. If machine-controller-manager fails with the Node drain because of misconfigured PDBs, then this should be properly flagged in the Machine status and provider extension should only deal with the Machine/MachineDeployment statuses. Let me known if there are objections. From now I will refrain from proposing any PR.

/cc @rfranzke @prashanth26

**Comment by rfranzke** [comment] 2021-01-25 06:54
Thanks for the summary @ialidzhikov. IIUC you propose that MCM, when it initiates a node drain, checks if there are problematic PDBs and if yes, it will populate this information into the machine status. Then the worker health check controller can simply read this and populate it to its own conditions (from where it will be picked up by the shoot care controller), right?

**Comment by ialidzhikov** [comment] 2021-01-25 08:24
> Thanks for the summary @ialidzhikov. IIUC you propose that MCM, when it initiates a node drain, checks if there are problematic PDBs and if yes, it will populate this information into the machine status. Then the worker health check controller can simply read this and populate it to its own conditions (from where it will be picked up by the shoot care controller), right?

Yes, this is my proposal.

**Comment by prashanth26** [comment] 2021-01-27 10:14
> I strongly believe that machine-controller-manager should maintain similar errorCodes in the Machine status. It is not the job of provider extension to check similar things and it simply does not scale. If machine-controller-manager fails with the Node drain because of misconfigured PDBs, then this should be properly flagged in the Machine status and provider extension should only deal with the Machine/MachineDeployment statuses.

I would second (probably third as Rafael seconded it :) )  with this proposal.

**Closed as completed** 2021-03-04 07:18 UTC
Labels: kind/enhancement, area/ops-productivity
